# This is a basic workflow to help you get started with Actions

name: Angular Deploy

# Controls when the workflow will run
on:
  push:
    branches:
    - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy Angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with: 
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: production
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/personal_website
        
permissions:
  contents: write
